import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(236, 236, 236)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"Text_2":{"styles":{
  width: Oreframework.getW(196.2,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(42.1875,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(102.6,318,560),
  textAlignVertical: "auto",
  zIndex: 5,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 72.1875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50005","txtctrlcaption":"Harris BG","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_3":{"styles":{
  width: Oreframework.getW(196.6,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(70.1875,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(102.25,318,560),
  textAlignVertical: "auto",
  zIndex: 10,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 100.1875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50006","txtctrlcaption":"Check In/Check Out","chkisenable":"false","txtctrlname":"Text_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_4":{"styles":{
  width: Oreframework.getW(196.6,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(97.9875,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(101,318,560),
  textAlignVertical: "auto",
  zIndex: 11,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 127.9875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"03/05/23","chkisenable":"false","txtctrlname":"Text_4","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_5":{"styles":{
  width: Oreframework.getW(196.6,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(125.587,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(100.375,318,560),
  textAlignVertical: "auto",
  zIndex: 12,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 155.587,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50008","txtctrlcaption":"02:30:54 PM","chkisenable":"false","txtctrlname":"Text_5","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Icon_1":{"styles":{
  icon: "arrow-back-outline",
  iconcolor: "rgb(255, 255, 255)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(37.625,318,560),
  height: Oreframework.getS(24.625,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  navigateTo: "Homepage",
  defaultDataType: "STRING",
  iconnpmtype: "Ionicons",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 36.625,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(12,318,560),left: Oreframework.getW(2,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50001","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Homepage",
  "icon": "arrow-back-outline",
  "iconcolor": "rgb(255, 255, 255)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Ionicons",
  "disabled": false
},"type":"icon"},"Square_1":{"styles":{
  width: Oreframework.getS(31.675,318,560),
  height: Oreframework.getS(31.675,318,560),
  borderRadius: 2,
  zIndex: 1,
  display: "flex"
},"imageStyle":{
  borderRadius: 2,
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(63, 81, 181)",
  borderRadius: 2,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F8889","txtctrlcaption":"Square","chkisenable":"false","txtctrlname":"Square_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Square",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(63, 81, 181)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Square"},"Text_1":{"styles":{
  textSize: 16,
  width: Oreframework.getW(133.625,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  fontSize: Oreframework.normalize(16,318,560),
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(12,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(92,318,560),
  textAlignVertical: "auto",
  zIndex: 9,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 42,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F10000","txtctrlcaption":"Attendance Filter","chkisenable":"false","txtctrlname":"Text_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":16,"selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Icon_2":{"styles":{
  icon: "filter",
  iconcolor: "rgb(255, 255, 255)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(37.625,318,560),
  height: Oreframework.getS(24.625,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  navigateTo: "Homepage",
  defaultDataType: "STRING",
  iconnpmtype: "anticon",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 38.625,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(14,318,560),left: Oreframework.getW(240,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F10001","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Homepage",
  "icon": "filter",
  "iconcolor": "rgb(255, 255, 255)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "anticon",
  "disabled": false
},"type":"icon"},"Square_2":{"styles":{
  width: Oreframework.getS(31.675,318,560),
  height: Oreframework.getS(31.675,318,560),
  borderRadius: 2,
  zIndex: 1,
  display: "flex"
},"imageStyle":{
  borderRadius: 2,
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(63, 81, 181)",
  borderRadius: 2,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F10002","txtctrlcaption":"Square","chkisenable":"false","txtctrlname":"Square_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Square",
  "navigateTo": "AdminParameterPage",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(63, 81, 181)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 0.5,
  "disabled": false
},"type":"Square"},"Icon_3":{"styles":{
  icon: "ios-download-outline",
  iconcolor: "rgb(255, 255, 255)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(37.625,318,560),
  height: Oreframework.getS(24.625,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  navigateTo: "Homepage",
  defaultDataType: "STRING",
  iconnpmtype: "Ionicons",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 38.437,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(13.812,318,560),left: Oreframework.getW(278,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F10003","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Homepage",
  "icon": "ios-download-outline",
  "iconcolor": "rgb(255, 255, 255)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Ionicons",
  "disabled": false
},"type":"icon"},"Square_3":{"styles":{
  width: Oreframework.getS(31.675,318,560),
  height: Oreframework.getS(31.675,318,560),
  borderRadius: 2,
  zIndex: 1,
  display: "flex"
},"imageStyle":{
  borderRadius: 2,
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(63, 81, 181)",
  borderRadius: 2,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F10004","txtctrlcaption":"Square","chkisenable":"false","txtctrlname":"Square_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Square",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(63, 81, 181)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Square"},"Flat_1":{"styles":{
  top: Oreframework.getH(60.2875,318,560),
  valMsgCode: ""
},"listViewItemStyle":{
  borderStyle: "solid",
  borderLeftColor: "rgb(204, 204, 204)",
  borderRightColor: "rgb(204, 204, 204)",
  borderTopColor: "rgb(204, 204, 204)",
  borderColor: "rgb(204, 204, 204)",
  borderBottomColor: "rgb(204, 204, 204)",
  borderWidth: 1,
  borderLeftWidth: 1,
  borderRightWidth: 1,
  borderTopWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 2,
  borderBottomRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderTopRightRadius: 2,
  borderTopLeftRadius: 2,
  height: Oreframework.getH(183,318,560)
},"imageStyle":{
  borderRadius: 0
},"searchViewStyle":{
  borderBottomWidth: 1,
  borderStyle: "solid"
},"searchTextStyle":{
  fontSize: Oreframework.normalize(12,318,560)
},"viewStyle":{
  width: Oreframework.getW(312.8,318,560),
  left: Oreframework.getW(4,318,560),
  display: "flex"
},"headingStyle":{},"contentStyle":{},"rightHeadingStyle":{},"Default":{"txtcontrolid":"F50002","txtctrlcaption":"Flat","chkisenable":"false","txtctrlname":"Flat_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "placeholderTextColor": "",
  "searchIconColor": "",
  "searchValue": "",
  "loaderStyle": "style1",
  "contentLoader": "none",
  "isrefreshing": false,
  "selectcount": "",
  "selectedItem": [],
  "dynamicComponentStyle": "Flat_1",
  "authorization": [],
  "customEvents": [],
  "pageparamauth": false,
  "paramavailable": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false,
  "isSeparator": false,
  "sep_size": 1,
  "onDemandLoading": false,
  "fromApi": false,
  "load": 10,
  "scrollComplete": false,
  "offset": 0,
  "onEndReachedThreshold": 0.5,
  "datamodelpagination": "",
  "datafieldpagination": "",
  "sep_color": "",
  "sep_style": "transparent",
  "autoHeight": true,
  "swipeEvents": false,
  "swipeStyle": "icon",
  "swipeColor": "",
  "swipe_iconsize": 25,
  "swipe_icontype": "regular",
  "swipe_fontFamily": "",
  "swipe_fontSize": "12",
  "activeOpacity": 1,
  "lts_iconColor": "",
  "lts_phColor": "",
  "placeholder": "Search from List",
  "isSearch": false,
  "data": [],
  "isHorizontal": false,
  "flatListType": "1",
  "noofColumn": 1,
  "data1": [],
  "background": "Color",
  "image_datasource": "URL",
  "source": "",
  "datasource": "service",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(232, 228, 228)",
  "locations": "",
  "gcolors": "",
  "datafield": "",
  "datamodel": "",
  "OreServiceLabel": "",
  "ca_backgroundColor": "",
  "ca_iconcolor": "",
  "ca_iconSize": 25,
  "ca_size": 25,
  "ca_icontype": "regular",
  "isMultiSelect": false,
  "selectedBGColor": "",
  "isMultiList": true,
  "datamodelsearch": "",
  "datafieldsearch": "",
  "onDemandSearch": false,
  "searchtextlength": 3,
  "isAnimation": false,
  "animationType": "Fade",
  "disabled": false,
  "noofColumnpadding": 0
},"swipeEvents":[],"type":"Flat","servicedatacollection":{}},"Icon_5":{"styles":{
  icon: "user",
  iconcolor: "rgb(31, 64, 200)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(78.7375,318,560),
  height: Oreframework.getS(79.7375,318,560),
  formvalidation: false,
  backgroundColor: "rgb(147, 180, 222)",
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Feather",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 192.7375,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(-191.4875,318,560),left: Oreframework.getW(10.3125,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50004","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_5","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "user",
  "iconcolor": "rgb(31, 64, 200)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Feather",
  "disabled": false
},"type":"icon"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":[]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


