import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(238, 239, 241)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"Icon_1":{"styles":{
  icon: "arrow-back-outline",
  iconcolor: "rgb(255, 255, 255)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(37.625,318,560),
  height: Oreframework.getS(24.625,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  navigateTo: "Homepage",
  defaultDataType: "STRING",
  iconnpmtype: "Ionicons",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 33.6136,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(8.9886,318,560),left: Oreframework.getW(1.99432,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50001","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Homepage",
  "icon": "arrow-back-outline",
  "iconcolor": "rgb(255, 255, 255)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Ionicons",
  "disabled": false
},"type":"icon"},"Square_1":{"styles":{
  width: Oreframework.getS(31.6719,318,560),
  height: Oreframework.getS(31.6719,318,560),
  borderRadius: 2,
  zIndex: 1,
  display: "flex"
},"imageStyle":{
  borderRadius: 2,
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(63, 81, 181)",
  borderRadius: 2,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 2,
  borderTopRightRadius: 2,
  borderBottomLeftRadius: 2,
  borderBottomRightRadius: 2,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F8889","txtctrlcaption":"Square","chkisenable":"false","txtctrlname":"Square_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Square",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(63, 81, 181)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Square"},"DatePicker_1":{"styles":{
  mode: "date",
  showIcon: true,
  is24Hour: false,
  format: "DD-MM-YYYY",
  serverFormat: "DD-MM-YYYY",
  iscurrentdate: false,
  iscurrentdatetime: false,
  iscurrenttime: false,
  defaultValue: "2-8-2023",
  ismincurrentdate: false,
  ismincurrentdatetime: false,
  ismaxcurrentdate: false,
  ismaxcurrentdatetime: false,
  iconPosition: "right",
  icon: "calendar",
  datepickerstyle: "style1",
  width: Oreframework.getW(279.516,318,560),
  defaultDataType: "STRING",
  valtype: "optional",
  allowFontScaling: false,
  androidMode: "default",
  height: Oreframework.getH(60.5,318,560),
  top: Oreframework.getH(129,318,560),
  bottom: Oreframework.getH(370.5,318,560),
  left: Oreframework.getW(14,318,560),
  right: Oreframework.getW(24.4844,318,560),
  valMsgCode: "",
  immediatevalidation: false,
  position: "absolute",
  modelsync: true,
  iconnpmtype: "anticon",
  zIndex: 5,
  onLoadListener: true,
  iconclass: "far fa-calendar-alt",
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 189.5,
  display: "flex"
},"textStyle":{
  height: Oreframework.getH((30/100)*60.5,318,560),
  color: "rgb(206, 23, 23)",
  textAlign: "left",
  display: "flex"
},"viewStyle":{
  width: Oreframework.getW(279.516,318,560),
  height: Oreframework.getH((70/100)*60.5,318,560),
  display: "flex"
},"title":"From Date","Default":{"txtcontrolid":"F10001","txtctrlcaption":"From Date","chkisenable":"false","txtctrlname":"DatePicker_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "mode": "date",
  "showIcon": true,
  "is24Hour": false,
  "format": "DD-MM-YYYY",
  "defaultValue": "2-8-2023",
  "minDate": "",
  "maxDate": "",
  "iconPosition": "right",
  "icon": "calendar",
  "iconColor": "",
  "datepickerstyle": "style1",
  "iscurrentdate": false,
  "iscurrentdatetime": false,
  "iscurrenttime": false,
  "ismincurrentdate": false,
  "ismincurrentdatetime": false,
  "ismaxcurrentdate": false,
  "ismaxcurrentdatetime": false,
  "datafield": "",
  "valtype": "optional",
  "serverValue": "",
  "serverFormat": "DD-MM-YYYY",
  "allowFontScaling": false,
  "androidMode": "default",
  "modelsync": true,
  "iconnpmtype": "anticon",
  "disabled": false
},"dateText":{},"dateInput":{
  borderWidth: 1,
  height: Oreframework.getH((70/100)*60.5,318,560),
  borderBottomWidth: 1
},"type":"date"},"DatePicker_2":{"styles":{
  mode: "date",
  showIcon: true,
  is24Hour: false,
  format: "DD-MM-YYYY",
  serverFormat: "DD-MM-YYYY",
  iscurrentdate: false,
  iscurrentdatetime: false,
  iscurrenttime: false,
  defaultValue: "2-8-2023",
  ismincurrentdate: false,
  ismincurrentdatetime: false,
  ismaxcurrentdate: false,
  ismaxcurrentdatetime: false,
  iconPosition: "right",
  icon: "calendar",
  datepickerstyle: "style1",
  width: Oreframework.getW(279.516,318,560),
  defaultDataType: "STRING",
  valtype: "optional",
  allowFontScaling: false,
  androidMode: "default",
  height: Oreframework.getH(60.5,318,560),
  top: Oreframework.getH(205.445,318,560),
  bottom: Oreframework.getH(294.062,318,560),
  left: Oreframework.getW(14,318,560),
  right: Oreframework.getW(24.4844,318,560),
  valMsgCode: "",
  immediatevalidation: false,
  position: "absolute",
  modelsync: true,
  iconnpmtype: "anticon",
  zIndex: 7,
  onLoadListener: true,
  iconclass: "far fa-calendar-alt",
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 265.945,
  display: "flex"
},"textStyle":{
  height: Oreframework.getH((30/100)*60.5,318,560),
  color: "rgb(206, 23, 23)",
  textAlign: "left",
  display: "flex"
},"viewStyle":{
  width: Oreframework.getW(279.516,318,560),
  height: Oreframework.getH((70/100)*60.5,318,560),
  display: "flex"
},"title":"To Date","Default":{"txtcontrolid":"F10002","txtctrlcaption":"To Date","chkisenable":"false","txtctrlname":"DatePicker_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "mode": "date",
  "showIcon": true,
  "is24Hour": false,
  "format": "DD-MM-YYYY",
  "defaultValue": "2-8-2023",
  "minDate": "",
  "maxDate": "",
  "iconPosition": "right",
  "icon": "calendar",
  "iconColor": "",
  "datepickerstyle": "style1",
  "iscurrentdate": false,
  "iscurrentdatetime": false,
  "iscurrenttime": false,
  "ismincurrentdate": false,
  "ismincurrentdatetime": false,
  "ismaxcurrentdate": false,
  "ismaxcurrentdatetime": false,
  "datafield": "",
  "valtype": "optional",
  "serverValue": "",
  "serverFormat": "DD-MM-YYYY",
  "allowFontScaling": false,
  "androidMode": "default",
  "modelsync": true,
  "iconnpmtype": "anticon",
  "disabled": false
},"dateText":{},"dateInput":{
  borderWidth: 1,
  height: Oreframework.getH((70/100)*60.5,318,560),
  borderBottomWidth: 1
},"type":"date"},"Rectangle_2":{"styles":{
  width: Oreframework.getW(304.875,318,560),
  height: Oreframework.getH(282.422,318,560),
  borderRadius: 0,
  position: "absolute",
  left: Oreframework.getW(6.375,318,560),
  zIndex: 4,
  top: Oreframework.getH(64.851,318,560),
  display: "flex"
},"imageStyle":{
  borderRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(255, 255, 255)",
  borderRadius: 0,
  transform: [{rotate:'0deg'}],
  borderWidth: 2,
  borderStyle: "solid",
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F10003","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(255, 255, 255)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"},"Text_1":{"styles":{
  textSize: 16,
  width: Oreframework.getW(133.625,318,560),
  height: Oreframework.getH(30,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  fontSize: Oreframework.normalize(16,318,560),
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(8,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(92,318,560),
  textAlignVertical: "auto",
  zIndex: 9,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 38,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F10005","txtctrlcaption":"Attendance Filter","chkisenable":"false","txtctrlname":"Text_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":16,"selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Button_2":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(107.516,318,560),
  height: Oreframework.getH(39.0625,318,560),
  backgroundColor: "rgb(149, 149, 149)",
  borderWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "rgb(195, 195, 195)",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(284,318,560),
  bottom: Oreframework.getH(236.938,318,560),
  left: Oreframework.getW(20.2969,318,560),
  right: Oreframework.getW(190.188,318,560),
  formvalidation: false,
  btnType: "normal",
  datasource: "service",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 10,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 323.0625,
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "rgb(248, 247, 247)",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F10006","txtctrlcaption":"Cancel","chkisenable":"false","txtctrlname":"Button_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Button_3":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(107.516,318,560),
  height: Oreframework.getH(39.0625,318,560),
  backgroundColor: "rgb(78, 147, 193)",
  borderWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(284,318,560),
  bottom: Oreframework.getH(236.938,318,560),
  left: Oreframework.getW(190.297,318,560),
  right: Oreframework.getW(20.1875,318,560),
  formvalidation: false,
  btnType: "normal",
  datasource: "service",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 11,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 323.0625,
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "rgb(248, 247, 247)",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F10007","txtctrlcaption":"View","chkisenable":"false","txtctrlname":"Button_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Text_2":{"styles":{
  textSize: 16,
  width: Oreframework.getW(294.625,318,560),
  height: Oreframework.getH(30,318,560),
  color: "rgba(0, 112, 186, 0.98)",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  fontSize: Oreframework.normalize(17,318,560),
  fontFamily: "Bold",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(85,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(11.5,318,560),
  textAlignVertical: "auto",
  zIndex: 9,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 115,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F10008","txtctrlcaption":"Attendance View","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":16,"selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":[]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


