import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(250, 248, 248)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"Header_1":{"styles":{},"textstyle":{
  type: "Style3",
  iconType: "regular",
  title: "Forgot password",
  displaylefticon: true,
  lefticon: "angle-left",
  lefticonformvalidation: false,
  lefticonsize: "25",
  lefticonsizevalue: 25,
  displayrighticon1: false,
  righticon1: "male",
  righticon1formvalidation: false,
  righticon1size: "25",
  righticon1sizevalue: 25,
  displayrighticon2: false,
  righticon2: "ellipsis-v",
  righticon2formvalidation: false,
  righticon2size: "25",
  righticon2sizevalue: 25,
  displayrighticon3: false,
  righticon3: "user",
  righticon3formvalidation: false,
  righticon3size: "25",
  righticon3sizevalue: 25,
  imagetype: "URL",
  textAlign: "center",
  lefticontype: "regular",
  righticon1type: "regular",
  righticon2type: "regular",
  righticon3type: "regular",
  defaultDataType: "STRING",
  statusBarProps: "default",
  barStyle: "default",
  pagebackgroundColor: false,
  navigateTo: "Login",
  righticon1npmtype: "fontisto",
  righticon2npmtype: "Entypo",
  righticon3npmtype: "anticon",
  lefticonnpmtype: "fontisto",
  zIndex: 1,
  iconnpmtype: "fontisto",
  iconclass: "far fa-heading",
  valMsgCode: "",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  fontSize: Oreframework.normalize(15,318,560),
  overall: 10,
  display: "flex"
},"Default":{"txtcontrolid":"F50001","txtctrlcaption":"Forgot password","chkisenable":"false","txtctrlname":"Header_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "righticon1formvalidation": false,
  "righticon2formvalidation": false,
  "righticon3formvalidation": false,
  "lefticonformvalidation": false,
  "textAlign": "center",
  "right1navigateTo": "",
  "right2navigateTo": "",
  "right3navigateTo": "",
  "navigateTo": "Login",
  "type": "Style3",
  "displaylefticon": true,
  "lefticon": "angle-left",
  "lefticoncolor": "",
  "lefticonsizevalue": 25,
  "lefticonsize": "25",
  "righticon1": "",
  "righticon1color": "",
  "righticon1size": "",
  "righticon1sizevalue": "",
  "righticon2": "",
  "righticon2color": "",
  "righticon2size": "",
  "righticon2sizevalue": "",
  "righticon3": "",
  "righticon3color": "",
  "righticon3size": "",
  "righticon3sizevalue": "",
  "imagetype": "URL",
  "backgroundImage": "",
  "title": "Forgot password",
  "displayrighticon1": false,
  "displayrighticon2": false,
  "displayrighticon3": false,
  "lefticontype": "regular",
  "righticon1type": "regular",
  "righticon2type": "regular",
  "righticon3type": "regular",
  "datamodel": "",
  "assetlink": require('../'),
  "datafield": "",
  "righticon1npmtype": "fontisto",
  "righticon2npmtype": "Entypo",
  "righticon3npmtype": "anticon",
  "lefticonnpmtype": "fontisto",
  "disabled": false
},"type":"Header"},"Text_1":{"styles":{
  textSize: 14,
  width: Oreframework.getW(307.513,318,560),
  height: Oreframework.getH(44.5375,318,560),
  color: "rgb(113, 109, 109)",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  fontSize: Oreframework.normalize(13,318,560),
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(177,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(5,318,560),
  textAlignVertical: "center",
  zIndex: 2,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 221.5375,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50002","txtctrlcaption":"Please enter Username and we will send a link to your mailid to reset your password","chkisenable":"false","txtctrlname":"Text_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":14,"selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Icon_1":{"styles":{
  icon: "ios-alert",
  iconcolor: "rgb(31, 64, 200)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(74.5375,318,560),
  height: Oreframework.getS(72.5375,318,560),
  formvalidation: false,
  backgroundColor: "rgb(147, 180, 222)",
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Ionicons",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 116.5375,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(44,318,560),left: Oreframework.getW(122,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50003","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "ios-alert",
  "iconcolor": "rgb(31, 64, 200)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Ionicons",
  "disabled": false
},"type":"icon"},"Text_2":{"styles":{
  width: Oreframework.getW(148.7,318,560),
  height: Oreframework.getH(23.0875,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  fontFamily: "Bold",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(129,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "uppercase",
  textDecorationLine: "none",
  left: Oreframework.getW(89.0795,318,560),
  textAlignVertical: "auto",
  zIndex: 4,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 152.0875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F10000","txtctrlcaption":"Forgot Password","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"TextBox_1":{"styles":{
  type: "Normal Text",
  secureTextEntry: false,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "default",
  placeHolder: "Enter your User ID",
  width: Oreframework.getW(308.625,318,560),
  height: Oreframework.getH(33,318,560),
  labelheight: 15,
  controlheight: 33.2,
  color: "rgb(51, 51, 51)",
  backgroundColor: "rgb(235, 232, 232)",
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "rgb(136, 136, 136)",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style2",
  iconnpmtype: "Entypo",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 4,
  onLoadListener: true,
  iconclass: "far fa-rectangle-landscape",
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 291.2,
  lefticonbox: "key",
  lefticonnpmtype: "Entypo",
  display: "flex"
},"textstyle":{
  width: Oreframework.getW(308.625,318,560),
  height: Oreframework.getH(15,318,560),
  color: "rgb(206, 23, 23)",
  textAlign: "left",
  display: "flex"
},"viewstyle":{
  height: Oreframework.getH(48.2,318,560),
  position: "absolute",
  top: Oreframework.getH(243,318,560),
  bottom: Oreframework.getH(229.6,318,560),
  left: Oreframework.getW(5,318,560),
  right: Oreframework.getW(4.775,318,560),
  zIndex: 4,
  display: "flex"
},"title":"User ID","Default":{"txtcontrolid":"F50004","txtctrlcaption":"User ID","chkisenable":"false","txtctrlname":"TextBox_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":false,"keyboardType":"default","placeHolder":"Enter your User ID","placeHolderTextColor":"","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"righticon":"","lefticon":"key","lefticonnpmtype":"Entypo","displayType":"style2","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"Button_1":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(123.2,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgb(63, 81, 181)",
  borderWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(29.80,318,560),
  bottom: Oreframework.getH(164.8,318,560),
  left: Oreframework.getW(5,318,560),
  right: Oreframework.getW(190.2,318,560),
  formvalidation: false,
  btnType: "submit",
  datasource: "direct",
  OreServiceLabel: "API#O433345#2#forgotpageres",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 4,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 356,
  datamodelbinding: "O433353#forgotpageres",
  modelmapdata: "API#O433345#2#forgotpageres",
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50005","txtctrlcaption":"Submit","chkisenable":"false","txtctrlname":"Button_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433345#2#forgotpageres",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "Registry",
      "param": true,
      "value": "mobuta",
      "children": [],
      "control": "mobuta"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "Username",
      "param": true,
      "value": "TextBox_1",
      "children": [],
      "control": "TextBox_1",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Button_3":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(123.2,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgb(189, 86, 86)",
  borderWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(29.80,318,560),
  bottom: Oreframework.getH(164.8,318,560),
  left: Oreframework.getW(189.313,318,560),
  right: Oreframework.getW(5.8875,318,560),
  formvalidation: false,
  navigateTo: "Login",
  btnType: "submit",
  datasource: "direct",
  OreServiceLabel: "API#O433345#2#forgotpageres",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 5,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 356,
  datamodelbinding: "O433353#forgotpageres",
  modelmapdata: "API#O433345#2#forgotpageres",
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"Cancel","chkisenable":"false","txtctrlname":"Button_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Login",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433345#2#forgotpageres",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "Registry",
      "param": true,
      "value": "mobuta",
      "children": [],
      "control": "mobuta"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "Username",
      "param": true,
      "value": "TextBox_1",
      "children": [],
      "control": "TextBox_1",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":[]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


