import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(255, 255, 255)",
  flex: 1,
  formvalidation: false,
  immediatevalidation: false,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"TextBox_1":{"styles":{
  type: "Normal Text",
  secureTextEntry: false,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "numeric",
  placeHolder: "Enter Your PIN",
  width: Oreframework.getW(300.087,318,560),
  height: Oreframework.getH(29,318,560),
  labelheight: 15,
  controlheight: 28.799999999999997,
  backgroundColor: "rgb(255, 255, 255)",
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "rgb(188, 188, 188)",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "EXP0001",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style1",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 4,
  onLoadListener: true,
  iconclass: "far fa-rectangle-landscape",
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 259.8,
  display: "flex"
},"textstyle":{
  width: Oreframework.getW(300.087,318,560),
  height: Oreframework.getH(15,318,560),
  color: "rgb(206, 23, 23)",
  textAlign: "left",
  display: "flex"
},"viewstyle":{
  height: Oreframework.getH(43.8,318,560),
  position: "absolute",
  top: Oreframework.getH(216,318,560),
  bottom: Oreframework.getH(301,318,560),
  left: Oreframework.getW(9.025,318,560),
  right: Oreframework.getW(9.2875,318,560),
  zIndex: 4,
  display: "flex"
},"title":"Enter Your PIN","Default":{"txtcontrolid":"F50004","txtctrlcaption":"Enter Your PIN","chkisenable":"false","txtctrlname":"TextBox_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":false,"keyboardType":"numeric","placeHolder":"Enter Your PIN","placeHolderTextColor":"","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"displayType":"style1","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"Button_3":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(148.15,318,560),
  height: Oreframework.getH(40,318,560),
  backgroundColor: "rgba(15, 165, 111, 0.89)",
  borderWidth: 1,
  borderRadius: 45,
  borderStyle: "solid",
  borderColor: "rgba(15, 165, 111, 0.89)",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(278,318,560),
  bottom: Oreframework.getH(242.8,318,560),
  left: Oreframework.getW(85,318,560),
  right: Oreframework.getW(85.25,318,560),
  formvalidation: true,
  btnType: "submit",
  datasource: "service",
  OreServiceLabel: "API#O433337#1#PINPageres",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  btndisplayType: "style2",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 7,
  iconclass: "far fa-rectangle-wide",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 318,
  modelmapdata: "API#O433337#1#PINPageres",
  datamodelbinding: "O433342#PINPageres",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"Next","chkisenable":"false","txtctrlname":"Button_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": true,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433337#1#PINPageres",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "Number",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psuserpin",
      "param": true,
      "value": "TextBox_1",
      "children": [
        {
          "id": 0,
          "rowdisable": "",
          "datatype": "String",
          "name": "psuserpin",
          "displayname": "Psuserpin",
          "datamodel": "",
          "value": "031107",
          "valtype": "M",
          "children": []
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "id": 1,
          "rowdisable": "",
          "datatype": "String",
          "name": "psdevcinfo",
          "displayname": "Psdevcinfo",
          "datamodel": "",
          "value": "ddh",
          "valtype": "M",
          "children": []
        ,"allowFontScaling":Oreframework.getAllowFontScaling()}
      ],
      "control": "TextBox_1",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "O433343",
      "appkey": "",
      "fieldname": "psuserpin",
      "name": "psdevcinfo",
      "param": true,
      "children": [
        {
          "code": "psuserpin",
          "name": "psuserpin",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "psdevcinfo",
          "name": "psdevcinfo",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()}
      ],
      "control": "dd",
      "dataModel": "",
      "dataField": "",
      "value": "dd"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Image_2":{"styles":{
  type: "Asset",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(147.275,318,560),
  height: Oreframework.getH(55.0625,318,560),
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(141,318,560),
  bottom: Oreframework.getH(364.737,318,560),
  left: Oreframework.getW(85,318,560),
  right: Oreframework.getW(86.125,318,560),
  opacity: 1,
  borderWidth: 0,
  zIndex: 2,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 196.0625,
  datasource: "direct",
  display: "flex"
},"Default":{"txtcontrolid":"F50012","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "https://studio.sterlo.io/img/image-icon.png",
  "blurRadius": 0,
  "type": "Asset",
  "assetlink": require('../assets/Library/Media/CompanyLogo.png'),
  "assetrefobjcode": "",
  "datafield": "",
  "resizeMode": "contain",
  "datamodel": "",
  "disabled": false
,"assetlinksvc":'../assets/Library/Media/CompanyLogo.png'},"type":"IMG"},"Button_4":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(148.15,318,560),
  height: Oreframework.getH(40,318,560),
  backgroundColor: "rgb(235, 235, 235)",
  borderWidth: 1,
  borderRadius: 45,
  borderStyle: "solid",
  borderColor: "rgb(235, 235, 235)",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "relative",
  top: Oreframework.getH(65.00,318,560),
  bottom: Oreframework.getH(137.8,318,560),
  left: Oreframework.getW(85,318,560),
  right: Oreframework.getW(85.25,318,560),
  formvalidation: false,
  btnType: "normal",
  datasource: "service",
  showDefaultMessage: true,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 8,
  iconclass: "far fa-rectangle-wide",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 423,
  display: "none"
},"textstyle":{
  color: "rgb(8, 0, 0)",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50014","txtctrlcaption":"Reset","chkisenable":"false","txtctrlname":"Button_4","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Image_3":{"styles":{
  type: "Asset",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(86,318,560),
  height: Oreframework.getH(31,318,560),
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(196.00,318,560),
  bottom: Oreframework.getH(15.8,318,560),
  left: Oreframework.getW(116,318,560),
  right: Oreframework.getW(116.4,318,560),
  opacity: 1,
  borderWidth: 0,
  zIndex: 9,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 545,
  datasource: "direct",
  display: "flex"
},"Default":{"txtcontrolid":"F50015","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "https://studio.sterlo.io/img/image-icon.png",
  "blurRadius": 0,
  "type": "Asset",
  "assetlink": require('../assets/Library/Media/CompanyLogo.png'),
  "assetrefobjcode": "",
  "datafield": "",
  "resizeMode": "contain",
  "datamodel": "",
  "disabled": false
,"assetlinksvc":'../assets/Library/Media/CompanyLogo.png'},"type":"IMG"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":[]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


