import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(255, 255, 255)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"UserID":{"styles":{
  type: "Normal Text",
  secureTextEntry: false,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "default",
  placeHolder: "Enter  Your User ID",
  placeHolderTextColor: "rgb(136, 136, 136)",
  width: Oreframework.getW(296.55,318,560),
  height: Oreframework.getH(29,318,560),
  labelheight: 15,
  controlheight: 29.4,
  backgroundColor: "rgb(255, 255, 255)",
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "EXP0001",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style1",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 1,
  onLoadListener: true,
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 241.4,
  iconclass: "far fa-rectangle-landscape",
  display: "flex"
},"textstyle":{
  width: Oreframework.getW(296.55,318,560),
  height: Oreframework.getH(15,318,560),
  color: "rgb(233, 45, 45)",
  textAlign: "left",
  display: "flex"
},"viewstyle":{
  height: Oreframework.getH(44.4,318,560),
  position: "absolute",
  top: Oreframework.getH(197,318,560),
  bottom: Oreframework.getH(319.4,318,560),
  left: Oreframework.getW(10,318,560),
  right: Oreframework.getW(11.85,318,560),
  zIndex: 1,
  display: "flex"
},"title":"User ID","Default":{"txtcontrolid":"F50001","txtctrlcaption":"User ID","chkisenable":"false","txtctrlname":"UserID","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":false,"keyboardType":"default","placeHolder":"Enter  Your User ID","placeHolderTextColor":"rgb(136, 136, 136)","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"displayType":"style1","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"Password":{"styles":{
  type: "Normal Text",
  secureTextEntry: true,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "default",
  placeHolder: "Enter Your Password",
  width: Oreframework.getW(296.55,318,560),
  height: Oreframework.getH(30,318,560),
  labelheight: 15,
  controlheight: 29.6,
  backgroundColor: "rgb(255, 255, 255)",
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "EXP0001",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style1",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 3,
  onLoadListener: true,
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 299.59999999999997,
  iconclass: "far fa-rectangle-landscape",
  righticonnpmtype: "anticon",
  display: "flex"
},"textstyle":{
  width: Oreframework.getW(296.55,318,560),
  height: Oreframework.getH(15,318,560),
  color: "rgb(233, 45, 45)",
  textAlign: "left",
  display: "flex"
},"viewstyle":{
  height: Oreframework.getH(44.4,318,560),
  position: "absolute",
  top: Oreframework.getH(255.2,318,560),
  bottom: Oreframework.getH(261.2,318,560),
  left: Oreframework.getW(10,318,560),
  right: Oreframework.getW(11.85,318,560),
  zIndex: 3,
  display: "flex"
},"title":"Password","Default":{"txtcontrolid":"F50002","txtctrlcaption":"Password","chkisenable":"false","txtctrlname":"Password","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":true,"keyboardType":"default","placeHolder":"Enter Your Password","placeHolderTextColor":"","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"righticon":"","lefticon":"","lefticonnpmtype":"","righticonnpmtype":"anticon","displayType":"style1","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"Text_2":{"styles":{
  width: Oreframework.getW(285.15,318,560),
  height: Oreframework.getH(22.2125,318,560),
  color: "rgb(22, 105, 178)",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "left",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(163,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(10,318,560),
  textAlignVertical: "auto",
  zIndex: 6,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 185.2125,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50006","txtctrlcaption":"Hello , Have a Great Day !!","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Icon_1":{"styles":{
  icon: "eye-slash",
  iconSize: "custom",
  size: 14,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(20,318,560),
  height: Oreframework.getS(20,318,560),
  formvalidation: false,
  backgroundSize: 20,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "20",
  zIndex: 7,
  customheight: 14,
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 295.7,
  iconclass: "far fa-icons",
  display: "flex"
},"viewStyle":{top: Oreframework.getH(275.7,318,560),left: Oreframework.getW(276.6,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "eye-slash",
  "iconcolor": "",
  "iconSize": "custom",
  "size": 14,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 20,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "20",
  "disabled": false
},"type":"icon"},"Image_3":{"styles":{
  type: "Asset",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(151.4,318,560),
  height: Oreframework.getH(46,318,560),
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(75.6,318,560),
  bottom: Oreframework.getH(439.2,318,560),
  left: Oreframework.getW(83,318,560),
  right: Oreframework.getW(84,318,560),
  opacity: 1,
  borderWidth: 0,
  zIndex: 9,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 121.6,
  datasource: "direct",
  display: "flex"
},"Default":{"txtcontrolid":"F50009","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "https://studio.sterlo.io/img/image-icon.png",
  "blurRadius": 0,
  "type": "Asset",
  "assetlink": require('../assets/Library/Media/CompanyLogo.png'),
  "assetrefobjcode": "",
  "datafield": "",
  "resizeMode": "contain",
  "datamodel": "",
  "disabled": false
,"assetlinksvc":'../assets/Library/Media/CompanyLogo.png'},"type":"IMG"},"Image_1":{"styles":{
  type: "Asset",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(127.412,318,560),
  height: Oreframework.getH(38.0875,318,560),
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "relative",
  top: Oreframework.getH(141.61,318,560),
  bottom: Oreframework.getH(81.5,318,560),
  left: Oreframework.getW(96.55,318,560),
  right: Oreframework.getW(94.4375,318,560),
  opacity: 1,
  borderWidth: 0,
  zIndex: 2,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 479.29949999999997,
  datasource: "direct",
  display: "none"
},"Default":{"txtcontrolid":"F8889","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_1","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "https://studio.sterlo.io/img/image-icon.png",
  "blurRadius": 0,
  "type": "Asset",
  "assetlink": require('../assets/Library/Media/CompanyLogo.png'),
  "assetrefobjcode": "",
  "datafield": "",
  "resizeMode": "contain",
  "datamodel": "",
  "disabled": false
,"assetlinksvc":'../assets/Library/Media/CompanyLogo.png'},"type":"IMG"},"Oval_1":{"styles":{
  width: Oreframework.getS(82.0875,318,560),
  height: Oreframework.getS(82.0875,318,560),
  borderRadius: Oreframework.getS(82.0875,318,560)/2,
  zIndex: 1,
  display: "none"
},"imageStyle":{
  borderRadius: Oreframework.getS(82.0875,318,560)/2
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(255, 255, 255)",
  borderRadius: Oreframework.getH(82.0875,318,560)/2,
  transform: [{rotate:'0deg'}, {scaleX: Oreframework.getS(170,318,560)/Oreframework.getS(82.0875,318,560)}],
  borderWidth: 1,
  borderColor: "rgb(251, 245, 245)",
  borderStyle: "solid",
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F8890","txtctrlcaption":"Oval","chkisenable":"false","txtctrlname":"Oval_1","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Oval",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(255, 255, 255)",
  "locations": [0,1],
  "gcolors": ['rgb(255, 255, 255)','rgb(39, 128, 227)'],
  "activeOpacity": 1,
  "disabled": false
},"type":"Oval"},"checkbox_1":{"styles":{
  disabled: false,
  tintColors: {
    true: "rgb(92, 213, 136)",
    false: "rgb(7, 6, 6)"
  },
  Value: false,
  flexDirection: "column",
  width: Oreframework.getW(128.8,318,560),
  height: Oreframework.getH(23.2125,318,560),
  defaultDataType: "ENUMS,ENUMN,STRING",
  position: "absolute",
  top: Oreframework.getH(18.50,318,560),
  selectionType: "single",
  bottom: Oreframework.getH(219.488,318,560),
  left: Oreframework.getW(10,318,560),
  right: Oreframework.getW(179.6,318,560),
  datasource: "direct",
  autobind: true,
  modelsync: true,
  zIndex: 3,
  valMsgCode: "",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 341.3125,
  iconclass: "fal fa-check-square",
  numberOfLines: "0",
  display: "flex"
},"textstyle":{
  color: "rgb(0, 134, 93)",
  textAlign: "auto",
  fontSize: Oreframework.normalize(12,318,560)
},"Default":{"txtcontrolid":"F50003","txtctrlcaption":"checkbox","chkisenable":"false","txtctrlname":"checkbox_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "Value": false,
  "tintColors": {
    "true": "rgb(92, 213, 136)",
    "false": "rgb(7, 6, 6)"
  },
  "datamodel": "",
  "selectionType": "single",
  "datafield": "",
  "datamodelbinding": "",
  "autobind": false,
  "nameField": "name",
  "valueField": "value",
  "flexDirection": "column",
  "selectItem": [],
  "selectItemCount": 0,
  "maxSelectCount": "",
  "data": [
    {
      "index": "1",
      "order": 1,
      "value": "1",
      "name": "Remember Me",
      "selected": false
    }
  ],
  "datasource": "direct",
  "selectSource": "",
  "selectObject": "",
  "selectBinding": "",
  "modelsync": true,
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false
},"type":"checkbox","servicedatacollection":{}},"Button_1":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(285.15,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgba(15, 165, 111, 0.89)",
  borderWidth: 1,
  borderRadius: 45,
  borderStyle: "solid",
  borderColor: "rgba(15, 165, 111, 0.89)",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(61.40,318,560),
  bottom: Oreframework.getH(164.8,318,560),
  left: Oreframework.getW(16,318,560),
  right: Oreframework.getW(17.25,318,560),
  formvalidation: true,
  btnType: "submit",
  datasource: "service",
  OreServiceLabel: "API#O433345#1#Loginres",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 4,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 396,
  modelmapdata: "API#O433345#1#Loginres",
  datamodelbinding: "O433346#Loginres",
  autobind: true,
  iconclass: "far fa-rectangle-wide",
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50004","txtctrlcaption":"Login","chkisenable":"false","txtctrlname":"Button_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": true,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433345#1#Loginres",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psusername",
      "param": true,
      "value": "UserID",
      "children": [],
      "control": "UserID",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psPasswrd",
      "param": true,
      "value": "Password",
      "children": [],
      "control": "Password",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 2,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "pnLanvage",
      "param": true,
      "value": "en",
      "children": [],
      "control": "en"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 3,
      "datatype": "String",
      "source": "Data Model",
      "datamodal": "O433342",
      "appkey": "",
      "fieldname": "tenantregkey",
      "name": "psregkey",
      "param": true,
      "value": "mobuta",
      "children": [
        {
          "code": "appnurl",
          "name": "appnurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "clntlogo",
          "name": "clntlogo",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "code",
          "name": "code",
          "datatype": "NUMBER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "copyrgt",
          "name": "copyrgt",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "hosturl",
          "name": "hosturl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "mobileapiurl",
          "name": "mobileapiurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "msg",
          "name": "msg",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tcd",
          "name": "tcd",
          "datatype": "INTEGER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tenantregkey",
          "name": "tenantregkey",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "saasregkey",
          "name": "saasregkey",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "usercode",
          "name": "usercode",
          "datatype": "INTEGER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()}
      ],
      "control": "mobuta"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Text_1":{"styles":{
  width: Oreframework.getW(128.8,318,560),
  height: Oreframework.getH(23.2125,318,560),
  color: "rgb(0, 134, 93)",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "right",
  fontSize: Oreframework.normalize(12,318,560),
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(18.50,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(177.75,318,560),
  navigateTo: "Forgotpassword",
  textAlignVertical: "auto",
  zIndex: 5,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 341.3125,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50005","txtctrlcaption":"Forgot Password ?","chkisenable":"false","txtctrlname":"Text_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"Forgotpassword","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Image_2":{"styles":{
  type: "Asset",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(90.8,318,560),
  height: Oreframework.getH(30.4875,318,560),
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(214.71,318,560),
  bottom: Oreframework.getH(16,318,560),
  left: Oreframework.getW(114,318,560),
  right: Oreframework.getW(113.6,318,560),
  opacity: 1,
  borderWidth: 0,
  zIndex: 8,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 544.7995,
  datasource: "direct",
  display: "flex"
},"Default":{"txtcontrolid":"F50008","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "https://studio.sterlo.io/img/image-icon.png",
  "blurRadius": 0,
  "type": "Asset",
  "assetlink": require('../assets/Library/Media/CompanyLogo.png'),
  "assetrefobjcode": "",
  "datafield": "",
  "resizeMode": "contain",
  "datamodel": "",
  "disabled": false
,"assetlinksvc":'../assets/Library/Media/CompanyLogo.png'},"type":"IMG"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":[]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


