import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(243, 242, 242)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"Header_1":{"styles":{},"textstyle":{
  type: "Style3",
  iconType: "regular",
  title: "Manage Device",
  displaylefticon: true,
  lefticon: "angle-left",
  lefticonformvalidation: false,
  lefticonsize: "25",
  lefticonsizevalue: 25,
  displayrighticon1: false,
  righticon1: "search1",
  righticon1formvalidation: false,
  righticon1size: "25",
  righticon1sizevalue: 25,
  displayrighticon2: false,
  righticon2: "ellipsis-v",
  righticon2formvalidation: false,
  righticon2size: "25",
  righticon2sizevalue: 25,
  displayrighticon3: false,
  righticon3: "user",
  righticon3formvalidation: false,
  righticon3size: "25",
  righticon3sizevalue: 25,
  imagetype: "URL",
  textAlign: "center",
  lefticontype: "regular",
  righticon1type: "regular",
  righticon2type: "regular",
  righticon3type: "regular",
  defaultDataType: "STRING",
  statusBarProps: "default",
  barStyle: "default",
  pagebackgroundColor: false,
  navigateTo: "Settings",
  righticon1npmtype: "anticon",
  righticon2npmtype: "Entypo",
  righticon3npmtype: "anticon",
  lefticonnpmtype: "fontisto",
  zIndex: 1,
  iconnpmtype: "fontisto",
  iconclass: "far fa-heading",
  valMsgCode: "",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  fontSize: Oreframework.normalize(15,318,560),
  overall: 10,
  display: "flex"
},"Default":{"txtcontrolid":"F50001","txtctrlcaption":"Manage Device","chkisenable":"false","txtctrlname":"Header_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "righticon1formvalidation": false,
  "righticon2formvalidation": false,
  "righticon3formvalidation": false,
  "lefticonformvalidation": false,
  "textAlign": "center",
  "right1navigateTo": "",
  "right2navigateTo": "",
  "right3navigateTo": "",
  "navigateTo": "Settings",
  "type": "Style3",
  "displaylefticon": true,
  "lefticon": "angle-left",
  "lefticoncolor": "",
  "lefticonsizevalue": 25,
  "lefticonsize": "25",
  "righticon1": "",
  "righticon1color": "",
  "righticon1size": "",
  "righticon1sizevalue": "",
  "righticon2": "",
  "righticon2color": "",
  "righticon2size": "",
  "righticon2sizevalue": "",
  "righticon3": "",
  "righticon3color": "",
  "righticon3size": "",
  "righticon3sizevalue": "",
  "imagetype": "URL",
  "backgroundImage": "",
  "title": "Manage Device",
  "displayrighticon1": false,
  "displayrighticon2": false,
  "displayrighticon3": false,
  "lefticontype": "regular",
  "righticon1type": "regular",
  "righticon2type": "regular",
  "righticon3type": "regular",
  "datamodel": "",
  "assetlink": require('../'),
  "datafield": "",
  "righticon1npmtype": "anticon",
  "righticon2npmtype": "Entypo",
  "righticon3npmtype": "anticon",
  "lefticonnpmtype": "fontisto",
  "disabled": false
},"type":"Header"},"Icon_1":{"styles":{
  icon: "user",
  iconcolor: "rgb(31, 64, 200)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(76.9375,318,560),
  height: Oreframework.getS(75.9375,318,560),
  formvalidation: false,
  backgroundColor: "rgb(147, 180, 222)",
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Entypo",
  zIndex: 3,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 119.9375,
  display: "flex"
},"viewStyle":{top: Oreframework.getH(44,318,560),left: Oreframework.getW(121,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50003","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "user",
  "iconcolor": "rgb(31, 64, 200)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Entypo",
  "disabled": false
},"type":"icon"},"Button_1":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(170.8,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgb(63, 81, 181)",
  borderWidth: 1,
  borderRadius: 2,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(234,318,560),
  bottom: Oreframework.getH(251.8,318,560),
  left: Oreframework.getW(74,318,560),
  right: Oreframework.getW(73.6,318,560),
  formvalidation: false,
  btnType: "submit",
  datasource: "direct",
  OreServiceLabel: "API#O433711#1#Activationresponse",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 4,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 269,
  datamodelbinding: "O433723#Activationresponse",
  modelmapdata: "API#O433711#1#Activationresponse",
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50005","txtctrlcaption":"Activate","chkisenable":"false","txtctrlname":"Button_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433711#1#Activationresponse",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psSql",
      "param": true,
      "value": "TextBox_2",
      "children": [],
      "control": "TextBox_2",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psTableName",
      "param": true,
      "value": "uisp_Up_Mbl_MobileDeviceId",
      "children": [],
      "control": "uisp_Up_Mbl_MobileDeviceId"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 2,
      "datatype": "String",
      "source": "Data Model",
      "datamodal": "O433342",
      "appkey": "",
      "fieldname": "tenantregkey",
      "name": "PsRegistry",
      "param": true,
      "children": [
        {
          "code": "appnurl",
          "name": "appnurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "clntlogo",
          "name": "clntlogo",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "code",
          "name": "code",
          "datatype": "INTEGER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "copyrgt",
          "name": "copyrgt",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "hosturl",
          "name": "hosturl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "mobileapiurl",
          "name": "mobileapiurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "msg",
          "name": "msg",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tcd",
          "name": "tcd",
          "datatype": "NUMBER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tenantregkey",
          "name": "tenantregkey",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "saasregkey",
          "name": "saasregkey",
          "datatype": "NULL"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "usercode",
          "name": "usercode",
          "datatype": "NULL"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()}
      ],
      "control": "mobuta",
      "value": "mobuta"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Text_1":{"styles":{
  width: Oreframework.getW(316.6,318,560),
  height: Oreframework.getH(23.4,318,560),
  datamodel: "O433364#EmployeeProfile",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(130,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(1,318,560),
  datafield: "empname",
  textAlignVertical: "auto",
  zIndex: 8,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 153.4,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50008","txtctrlcaption":"Harris BG","chkisenable":"false","txtctrlname":"Text_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"empname","datamodel":"O433364#EmployeeProfile","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_2":{"styles":{
  width: Oreframework.getW(316.6,318,560),
  height: Oreframework.getH(22.4,318,560),
  datamodel: "O433364#EmployeeProfile",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(156,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(1,318,560),
  datafield: "empcontno",
  textAlignVertical: "auto",
  zIndex: 9,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 178.4,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50009","txtctrlcaption":"9751481308","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"empcontno","datamodel":"O433364#EmployeeProfile","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_3":{"styles":{
  width: Oreframework.getW(316.6,318,560),
  height: Oreframework.getH(20.4,318,560),
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(182,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(1,318,560),
  textAlignVertical: "auto",
  zIndex: 10,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 202.4,
  iconclass: "far fa-text",
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50010","txtctrlcaption":"Device Name","chkisenable":"false","txtctrlname":"Text_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"TextBox_2":{"styles":{
  type: "Normal Text",
  secureTextEntry: false,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "default",
  width: Oreframework.getW(24.2,318,560),
  height: Oreframework.getH(30,318,560),
  labelheight: 15,
  controlheight: 30,
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 0,
  borderStyle: "solid",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style1",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 11,
  onLoadListener: true,
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: "45",
  display: "none"
},"textstyle":{
  width: Oreframework.getW(24.2,318,560),
  height: Oreframework.getH(15,318,560),
  textAlign: "left",
  display: "none"
},"viewstyle":{
  height: Oreframework.getH(45,318,560),
  position: "relative",
  bottom: Oreframework.getH(475.8,318,560),
  left: Oreframework.getW(18.2,318,560),
  right: Oreframework.getW(276,318,560),
  zIndex: 11,
  display: "none"
},"title":"Text Box","Default":{"txtcontrolid":"F50011","txtctrlcaption":"Text Box","chkisenable":"false","txtctrlname":"TextBox_2","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":false,"keyboardType":"default","placeHolder":"","placeHolderTextColor":"","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"displayType":"style1","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"TextBox_1":{"styles":{
  type: "Normal Text",
  secureTextEntry: false,
  maxLength: 1000,
  multiline: false,
  numOfLines: 1,
  keyboardType: "default",
  placeHolder: "Enter Your User Id",
  width: Oreframework.getW(283,318,560),
  height: Oreframework.getH(30,318,560),
  labelheight: 15,
  controlheight: 30,
  borderWidth: 1,
  borderBottomWidth: 1,
  borderRadius: 0,
  borderStyle: "solid",
  textAlign: "left",
  defaultDataType: "STRING",
  valtype: "optional",
  prefix: "$",
  delimiter: ",",
  separator: ".",
  precision: 2,
  thousandSpacing: 3,
  valMsgCode: "EXP0001",
  immediatevalidation: false,
  modelsync: true,
  textboxtype: "style1",
  lefticonsizevalue: 15,
  righticonsizevalue: "15",
  zIndex: 2,
  onLoadListener: true,
  iconclass: "far fa-rectangle-landscape",
  formvalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 376,
  display: "none"
},"textstyle":{
  width: Oreframework.getW(283,318,560),
  height: Oreframework.getH(15,318,560),
  textAlign: "left",
  display: "none"
},"viewstyle":{
  height: Oreframework.getH(45,318,560),
  position: "relative",
  top: Oreframework.getH(62.00,318,560),
  bottom: Oreframework.getH(144.8,318,560),
  left: Oreframework.getW(19.2,318,560),
  right: Oreframework.getW(16.2,318,560),
  zIndex: 2,
  display: "none"
},"title":"User ID","Default":{"txtcontrolid":"F50002","txtctrlcaption":"User ID","chkisenable":"false","txtctrlname":"TextBox_1","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"type":"Normal Text","datamodel":"","multiline":false,"maxLength":1000,"numOfLines":1,"secureTextEntry":false,"keyboardType":"default","placeHolder":"Enter Your User Id","placeHolderTextColor":"","value":"","datafield":"","valtype":"optional","prefix":"$","delimiter":",","separator":".","precision":2,"thousandSpacing":3,"modelsync":true,"disabled":false,"displayType":"style1","righticonSize":20,"lefticonSize":20,"lefticonColor":"","righticonColor":"","allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Textarea"},"Button_2":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(171.4,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgb(189, 86, 86)",
  borderWidth: 1,
  borderRadius: 2,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "relative",
  top: Oreframework.getH(142.00,318,560),
  bottom: Oreframework.getH(74.8,318,560),
  left: Oreframework.getW(73,318,560),
  right: Oreframework.getW(74,318,560),
  formvalidation: true,
  btnType: "submit",
  datasource: "direct",
  OreServiceLabel: "API#O433711#1#Activationresponse",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 4,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 446,
  datamodelbinding: "O433723#Activationresponse",
  modelmapdata: "API#O433711#1#Activationresponse",
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "none"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50006","txtctrlcaption":"Deactivate","chkisenable":"false","txtctrlname":"Button_2","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": true,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "API#O433711#1#Activationresponse",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [
    {
      "id": 0,
      "datatype": "String",
      "source": "Page Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psSql",
      "param": true,
      "value": "TextBox_2",
      "children": [],
      "control": "TextBox_2",
      "dataModel": "",
      "dataField": ""
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 1,
      "datatype": "String",
      "source": "Static Value",
      "datamodal": "",
      "appkey": "",
      "fieldname": "",
      "name": "psTableName",
      "param": true,
      "value": "uisp_Up_Mbl_MobileDeviceId",
      "children": [],
      "control": "uisp_Up_Mbl_MobileDeviceId"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()},
    {
      "id": 2,
      "datatype": "String",
      "source": "Data Model",
      "datamodal": "O433342",
      "appkey": "",
      "fieldname": "tenantregkey",
      "name": "PsRegistry",
      "param": true,
      "children": [
        {
          "code": "appnurl",
          "name": "appnurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "clntlogo",
          "name": "clntlogo",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "code",
          "name": "code",
          "datatype": "INTEGER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "copyrgt",
          "name": "copyrgt",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "hosturl",
          "name": "hosturl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "mobileapiurl",
          "name": "mobileapiurl",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "msg",
          "name": "msg",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tcd",
          "name": "tcd",
          "datatype": "NUMBER"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "tenantregkey",
          "name": "tenantregkey",
          "datatype": "STRING"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "saasregkey",
          "name": "saasregkey",
          "datatype": "NULL"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()},
        {
          "code": "usercode",
          "name": "usercode",
          "datatype": "NULL"
        ,"allowFontScaling":Oreframework.getAllowFontScaling()}
      ],
      "control": "mobuta",
      "value": "mobuta"
    ,"allowFontScaling":Oreframework.getAllowFontScaling()}
  ],
  "paramavailable": true,
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"},"Rectangle_2":{"styles":{
  width: Oreframework.getW(303.8,318,560),
  height: Oreframework.getH(170,318,560),
  borderRadius: 0,
  position: "relative",
  left: Oreframework.getW(7.4,318,560),
  zIndex: 1,
  top: Oreframework.getH(33.00,318,560),
  display: "none"
},"imageStyle":{
  borderRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0
},"viewStyle":{
  width: "100%",
  height: "100%",
  borderRadius: 0,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_2","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":["Text_1","Text_2"]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


