import Oreframework from 'react-native-oreopscore/components/OreOPS/general/Ore_Framework';

 const PropertyJson={"Page_01":{"styles":{
  backgroundColor: "rgb(243, 243, 243)",
  eautobind: "OnShow",
  flex: 1,
  resolutions: "android",
  ideheight: 560,
  idewidth: 318,
  formvalidation: false,
  immediatevalidation: false
},"Default":{"txtcontrolid":"50000","txtctrlcaption":"","chkisenable":"","txtctrlname":"Page_01","mobiledisplay":"","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "backgroundImage": "",
  "height": 560,
  "width": 318
}},"APIJSON":[],"CONNECTORJSON":[],"Header_1":{"styles":{},"textstyle":{
  type: "Style3",
  iconType: "regular",
  title: "Settings",
  displaylefticon: true,
  lefticon: "angle-left",
  lefticonformvalidation: false,
  lefticonsize: "25",
  lefticonsizevalue: 25,
  displayrighticon1: false,
  righticon1: "search1",
  righticon1formvalidation: false,
  righticon1size: "25",
  righticon1sizevalue: 25,
  displayrighticon2: false,
  righticon2: "home",
  righticon2formvalidation: false,
  righticon2size: "25",
  righticon2sizevalue: 25,
  displayrighticon3: false,
  righticon3: "user",
  righticon3formvalidation: false,
  righticon3size: "25",
  righticon3sizevalue: 25,
  imagetype: "URL",
  textAlign: "center",
  lefticontype: "regular",
  righticon1type: "regular",
  righticon2type: "regular",
  righticon3type: "regular",
  defaultDataType: "STRING",
  statusBarProps: "default",
  barStyle: "default",
  pagebackgroundColor: false,
  navigateTo: "Homepage",
  right1navigateTo: "Homepage",
  right2navigateTo: "Homepage",
  righticon1npmtype: "anticon",
  righticon2npmtype: "fontisto",
  righticon3npmtype: "anticon",
  lefticonnpmtype: "fontisto",
  zIndex: 1,
  iconnpmtype: "fontisto",
  iconclass: "far fa-heading",
  valMsgCode: "",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  fontSize: Oreframework.normalize(15,318,560),
  overall: 10,
  display: "flex"
},"Default":{"txtcontrolid":"F50001","txtctrlcaption":"Settings","chkisenable":"false","txtctrlname":"Header_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "righticon1formvalidation": false,
  "righticon2formvalidation": false,
  "righticon3formvalidation": false,
  "lefticonformvalidation": false,
  "textAlign": "center",
  "right1navigateTo": "Homepage",
  "right2navigateTo": "Homepage",
  "right3navigateTo": "",
  "navigateTo": "Homepage",
  "type": "Style3",
  "displaylefticon": true,
  "lefticon": "angle-left",
  "lefticoncolor": "",
  "lefticonsizevalue": 25,
  "lefticonsize": "25",
  "righticon1": "",
  "righticon1color": "",
  "righticon1size": "",
  "righticon1sizevalue": "",
  "righticon2": "",
  "righticon2color": "",
  "righticon2size": "",
  "righticon2sizevalue": "",
  "righticon3": "",
  "righticon3color": "",
  "righticon3size": "",
  "righticon3sizevalue": "",
  "imagetype": "URL",
  "backgroundImage": "",
  "title": "Settings",
  "displayrighticon1": false,
  "displayrighticon2": false,
  "displayrighticon3": false,
  "lefticontype": "regular",
  "righticon1type": "regular",
  "righticon2type": "regular",
  "righticon3type": "regular",
  "datamodel": "",
  "assetlink": require('../'),
  "datafield": "",
  "righticon1npmtype": "anticon",
  "righticon2npmtype": "fontisto",
  "righticon3npmtype": "anticon",
  "lefticonnpmtype": "fontisto",
  "disabled": false
},"type":"Header"},"Text_2":{"styles":{
  width: Oreframework.getW(223.797,318,560),
  height: Oreframework.getH(26.1875,318,560),
  color: "rgb(12, 12, 12)",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(269.1,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(48,318,560),
  navigateTo: "ManageDevice",
  textAlignVertical: "auto",
  zIndex: 6,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 295.2875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50006","txtctrlcaption":"Manage Device","chkisenable":"false","txtctrlname":"Text_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"ManageDevice","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_3":{"styles":{
  width: Oreframework.getW(223.797,318,560),
  height: Oreframework.getH(26.1875,318,560),
  color: "rgb(2, 2, 2)",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(217,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(48,318,560),
  navigateTo: "Profile",
  textAlignVertical: "auto",
  zIndex: 7,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 243.1875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50010","txtctrlcaption":"Profile","chkisenable":"false","txtctrlname":"Text_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"Profile","datafield":"","datamodel":"","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_6":{"styles":{
  width: Oreframework.getW(287.641,318,560),
  height: Oreframework.getH(23.2188,318,560),
  color: "rgb(255, 255, 255)",
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(20,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(13.9584,318,560),
  datafield: "company",
  textAlignVertical: "auto",
  zIndex: 19,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 43.2188,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50014","txtctrlcaption":"Tactive ","chkisenable":"false","txtctrlname":"Text_6","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"company","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Rectangle_3":{"styles":{
  width: Oreframework.getW(306.094,318,560),
  height: Oreframework.getH(41.4219,318,560),
  borderRadius: 5,
  position: "absolute",
  left: Oreframework.getW(4,318,560),
  zIndex: 18,
  top: Oreframework.getH(13,318,560),
  display: "flex"
},"imageStyle":{
  borderRadius: 5,
  borderTopLeftRadius: 5,
  borderTopRightRadius: 5,
  borderBottomLeftRadius: 5,
  borderBottomRightRadius: 5
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(119, 191, 243)",
  borderRadius: 5,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 5,
  borderTopRightRadius: 5,
  borderBottomLeftRadius: 5,
  borderBottomRightRadius: 5,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F50015","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_3","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(119, 191, 243)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"},"Rectangle_4":{"styles":{
  width: Oreframework.getW(310.125,318,560),
  height: Oreframework.getH(154.297,318,560),
  borderRadius: 5,
  position: "absolute",
  left: Oreframework.getW(4,318,560),
  zIndex: 1,
  top: Oreframework.getH(11,318,560),
  display: "flex"
},"imageStyle":{
  borderRadius: 5,
  borderTopLeftRadius: 5,
  borderTopRightRadius: 5,
  borderBottomLeftRadius: 5,
  borderBottomRightRadius: 5
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgb(248, 248, 248)",
  borderRadius: 5,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderColor: "rgb(106, 130, 211)",
  borderStyle: "solid",
  borderTopLeftRadius: 5,
  borderTopRightRadius: 5,
  borderBottomLeftRadius: 5,
  borderBottomRightRadius: 5,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F50016","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_4","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgb(248, 248, 248)",
  "locations": [0,0.95],
  "gcolors": ['rgb(255, 255, 255)','rgb(92, 156, 228)'],
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"},"Text_7":{"styles":{
  width: Oreframework.getW(184.516,318,560),
  height: Oreframework.getH(21.1875,318,560),
  color: "rgb(18, 91, 252)",
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(100,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(118.109,318,560),
  datafield: "designation",
  textAlignVertical: "auto",
  zIndex: 5,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 121.1875,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50017","txtctrlcaption":"Role","chkisenable":"false","txtctrlname":"Text_7","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"designation","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_8":{"styles":{
  width: Oreframework.getW(184.516,318,560),
  height: Oreframework.getH(21.1875,318,560),
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(135.781,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(118.109,318,560),
  datafield: "project",
  textAlignVertical: "auto",
  zIndex: 6,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 156.9685,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50018","txtctrlcaption":"Head office ,Chennai","chkisenable":"false","txtctrlname":"Text_8","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"project","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_9":{"styles":{
  width: Oreframework.getW(184.516,318,560),
  height: Oreframework.getH(21.1875,318,560),
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(67.461,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(118.109,318,560),
  datafield: "empname",
  textAlignVertical: "auto",
  zIndex: 4,
  iconclass: "far fa-text",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 88.6485,
  display: "flex",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50019","txtctrlcaption":"Harris BG","chkisenable":"false","txtctrlname":"Text_9","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"empname","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Image_2":{"styles":{
  type: "URL",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "contain",
  width: Oreframework.getW(87.3125,318,560),
  height: Oreframework.getH(87.9688,318,560),
  borderRadius: 100,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "absolute",
  top: Oreframework.getH(69,318,560),
  bottom: Oreframework.getH(363.031,318,560),
  left: Oreframework.getW(12,318,560),
  right: Oreframework.getW(212.688,318,560),
  datafield: "imglink",
  opacity: 1,
  borderWidth: 0,
  zIndex: 20,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 156.9688,
  datamodel: "O433358#Avatar",
  display: "flex"
},"Default":{"txtcontrolid":"F50020","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_2","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderRadius: 100,
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "",
  "blurRadius": 0,
  "type": "URL",
  "assetlink": require('../'),
  "assetrefobjcode": "",
  "datafield": "imglink",
  "resizeMode": "contain",
  "datamodel": "O433358#Avatar",
  "disabled": false,
  "assetimage64": ""
,"assetlinksvc":'../'},"type":"IMG"},"Icon_6":{"styles":{
  icon: "male",
  iconcolor: "rgb(40, 115, 211)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(43.7969,318,560),
  height: Oreframework.getS(44.7969,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  navigateTo: "Profile",
  defaultDataType: "STRING",
  iconnpmtype: "fontisto",
  zIndex: 22,
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 248.49089999999998,
  iconclass: "far fa-icons",
  display: "flex"
},"viewStyle":{top: Oreframework.getH(203.694,318,560),left: Oreframework.getW(-1,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50022","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_6","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "Profile",
  "icon": "male",
  "iconcolor": "rgb(40, 115, 211)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "fontisto",
  "disabled": false
},"type":"icon"},"Icon_7":{"styles":{
  icon: "assignment-ind",
  iconcolor: "rgb(40, 115, 211)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(43.7969,318,560),
  height: Oreframework.getS(44.7969,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Material Icons",
  zIndex: 23,
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 302.58889999999997,
  iconclass: "far fa-icons",
  display: "flex"
},"viewStyle":{top: Oreframework.getH(257.792,318,560),left: Oreframework.getW(-1,318,560),position: 'absolute', alignItems: 'center'},"Default":{"txtcontrolid":"F50023","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_7","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "assignment-ind",
  "iconcolor": "rgb(40, 115, 211)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Material Icons",
  "disabled": false
},"type":"icon"},"Icon_3":{"styles":{
  icon: "chevron-right",
  iconcolor: "rgb(2, 2, 2)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(50,318,560),
  height: Oreframework.getS(50,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Feather",
  zIndex: 4,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 629.5,
  display: "none"
},"viewStyle":{top: Oreframework.getH(276.91,318,560),left: Oreframework.getW(-2,318,560),position: 'relative', alignItems: 'center'},"Default":{"txtcontrolid":"F50004","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_3","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "chevron-right",
  "iconcolor": "rgb(2, 2, 2)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Feather",
  "disabled": false
},"type":"icon"},"Rectangle_1":{"styles":{
  width: Oreframework.getW(317.594,318,560),
  height: Oreframework.getH(43.3906,318,560),
  borderRadius: 0,
  position: "relative",
  left: Oreframework.getW(0,318,560),
  zIndex: 1,
  top: Oreframework.getH(276.91,318,560),
  display: "none"
},"imageStyle":{
  borderRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgba(49, 94, 166, 0.85)",
  borderRadius: 0,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F50007","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_1","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgba(49, 94, 166, 0.85)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"},"Rectangle_2":{"styles":{
  width: Oreframework.getW(317.594,318,560),
  height: Oreframework.getH(43.3906,318,560),
  borderRadius: 0,
  position: "relative",
  left: Oreframework.getW(0,318,560),
  zIndex: 1,
  top: Oreframework.getH(219.61,318,560),
  display: "none"
},"imageStyle":{
  borderRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0
},"viewStyle":{
  width: "100%",
  height: "100%",
  backgroundColor: "rgba(49, 94, 166, 0.85)",
  borderRadius: 0,
  transform: [{rotate:'0deg'}],
  borderWidth: 1,
  borderStyle: "solid",
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  opacity: 1,
  elevation: 0
},"Default":{"txtcontrolid":"F50008","txtctrlcaption":"Rectangle","chkisenable":"false","txtctrlname":"Rectangle_2","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "type": "Rectangle",
  "navigateTo": "",
  "background": "Color",
  "source": "",
  "datasource": "URL",
  "assetlink": require('../'),
  "blurRadius": "",
  "resizeMode": "cover",
  "backgroundColor": "rgba(49, 94, 166, 0.85)",
  "locations": "",
  "gcolors": "",
  "activeOpacity": 1,
  "disabled": false
},"type":"Rectangle"},"Icon_4":{"styles":{
  icon: "chevron-right",
  iconcolor: "rgb(2, 2, 2)",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(50,318,560),
  height: Oreframework.getS(50,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Feather",
  zIndex: 4,
  iconclass: "far fa-icons",
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 568.889,
  display: "none"
},"viewStyle":{top: Oreframework.getH(216.30,318,560),left: Oreframework.getW(-2,318,560),position: 'relative', alignItems: 'center'},"Default":{"txtcontrolid":"F50009","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_4","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "chevron-right",
  "iconcolor": "rgb(2, 2, 2)",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Feather",
  "disabled": false
},"type":"icon"},"Text_4":{"styles":{
  width: Oreframework.getW(312.172,318,560),
  height: Oreframework.getH(24.375,318,560),
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  defaultDataType: "STRING",
  position: "relative",
  top: Oreframework.getH(121.89,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(12,318,560),
  datafield: "empname",
  textAlignVertical: "auto",
  zIndex: 11,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 448.854,
  iconclass: "far fa-text",
  display: "none",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50011","txtctrlcaption":"Harris BG","chkisenable":"false","txtctrlname":"Text_4","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"empname","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Text_5":{"styles":{
  width: Oreframework.getW(312.172,318,560),
  height: Oreframework.getH(24.375,318,560),
  datamodel: "O433357#homeres",
  borderRadius: 1,
  borderStyle: "solid",
  textAlign: "center",
  defaultDataType: "STRING",
  position: "relative",
  top: Oreframework.getH(196.40,318,560),
  numberOfLines: 0,
  selectable: false,
  textTransform: "none",
  textDecorationLine: "none",
  left: Oreframework.getW(3,318,560),
  datafield: "designation",
  textAlignVertical: "auto",
  zIndex: 12,
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 523.361,
  iconclass: "far fa-text",
  display: "none",
  valMsgCode: ""
},"Default":{"txtcontrolid":"F50012","txtctrlcaption":"9751481308","chkisenable":"false","txtctrlname":"Text_5","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{"numberOfLines":0,"textSize":"","selectable":false,"navigateTo":"","datafield":"designation","datamodel":"O433357#homeres","disabled":false,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"h1"},"Image_1":{"styles":{
  type: "URL",
  activeOpacity: 1,
  blurRadius: 0,
  resizeMode: "stretch",
  width: Oreframework.getW(87.3125,318,560),
  height: Oreframework.getH(87.9688,318,560),
  borderRadius: 100,
  borderStyle: "solid",
  defaultDataType: "STRING",
  position: "relative",
  top: Oreframework.getH(78.41,318,560),
  bottom: Oreframework.getH(51.0312,318,560),
  left: Oreframework.getW(115,318,560),
  right: Oreframework.getW(109.688,318,560),
  datafield: "imglink",
  opacity: 1,
  borderWidth: 0,
  zIndex: 20,
  iconclass: "fal fa-image",
  formvalidation: false,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 468.9688,
  datamodel: "O433358#Avatar",
  display: "none"
},"Default":{"txtcontrolid":"F50013","txtctrlcaption":"Image","chkisenable":"false","txtctrlname":"Image_1","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"imageStyle":{
  borderRadius: 100,
  borderStyle: "solid",
  borderWidth: 0
},"Property":{
  "activeOpacity": 1,
  "navigateTo": "",
  "source": "",
  "blurRadius": 0,
  "type": "URL",
  "assetlink": require('../'),
  "assetrefobjcode": "",
  "datafield": "imglink",
  "resizeMode": "stretch",
  "datamodel": "O433358#Avatar",
  "disabled": false,
  "assetimage64": ""
,"assetlinksvc":'../'},"type":"IMG"},"Icon_5":{"styles":{
  icon: "ios-home-outline",
  iconSize: 25,
  size: 25,
  type: "style1",
  activeOpacity: 0.5,
  borderRadius: 50,
  width: Oreframework.getS(50,318,560),
  height: Oreframework.getS(50,318,560),
  formvalidation: false,
  backgroundSize: 50,
  iconType: "regular",
  defaultDataType: "STRING",
  iconnpmtype: "Ionicons",
  zIndex: 21,
  valMsgCode: "",
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 635.8,
  iconclass: "far fa-icons",
  display: "none"
},"viewStyle":{top: Oreframework.getH(283.21,318,560),left: Oreframework.getW(195,318,560),position: 'relative', alignItems: 'center'},"Default":{"txtcontrolid":"F50021","txtctrlcaption":"Icon","chkisenable":"false","txtctrlname":"Icon_5","mobiledisplay":"none","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "icon": "ios-home-outline",
  "iconcolor": "",
  "iconSize": 25,
  "size": 25,
  "formvalidation": false,
  "type": "style1",
  "iconType": "regular",
  "activeOpacity": 0.5,
  "backgroundSize": 50,
  "datafield": "",
  "datamodel": "",
  "iconnpmtype": "Ionicons",
  "disabled": false
},"type":"icon"},"Button_1":{"styles":{
  buttonSize: "C",
  activeOpacity: 0.5,
  width: Oreframework.getW(286.625,318,560),
  height: Oreframework.getH(35,318,560),
  backgroundColor: "rgb(189, 86, 86)",
  borderWidth: 1,
  borderRadius: 5,
  borderStyle: "solid",
  borderColor: "#3F51B5",
  textAlign: "center",
  defaultDataType: "STRING,NUMBER,INTEGER",
  position: "absolute",
  top: Oreframework.getH(12.41,318,560),
  bottom: Oreframework.getH(170,318,560),
  left: Oreframework.getW(16,318,560),
  right: Oreframework.getW(9.375,318,560),
  formvalidation: false,
  btnType: "normal",
  datasource: "direct",
  showDefaultMessage: false,
  iconnpmtype: "anticon",
  activityindicator: false,
  indicatorColor: "rgb(255, 255, 255)",
  zIndex: 5,
  immediatevalidation: false,
  logoWidth: 0,
  logoHeight: 0,
  timeoutDuration: 0,
  animationDuration: 0,
  overall: 350,
  iconclass: "far fa-rectangle-wide",
  autobind: true,
  display: "flex"
},"textstyle":{
  color: "#ffffff",
  fontSize: Oreframework.normalize(14,318,560)
},"Default":{"txtcontrolid":"F50024","txtctrlcaption":"Logout","chkisenable":"false","txtctrlname":"Button_1","mobiledisplay":"flex","bgcolor":null,"bgimage":null,"canBackPress":"false"},"Property":{
  "navigateTo": "",
  "buttonSize": "C",
  "activeOpacity": 0.5,
  "formvalidation": false,
  "datafield": "",
  "datamodel": "",
  "modelmapdata": "",
  "background": "Color",
  "locations": "",
  "gcolors": "",
  "icon": "",
  "iconnpmtype": "anticon",
  "disabled": false,
  "authorization": [],
  "pageparamauth": false,
  "param": [],
  "headerjsondata": [],
  "pageparamheader": false
,"allowFontScaling":Oreframework.getAllowFontScaling()},"type":"Button"}}
 const Nanojson=[]
 const Paramjson=[]
 const Datamodel={"models":[{"modelcode":"O433342","modelname":"PINPageres"},{"modelcode":"O433343","modelname":"PINPage"},{"modelcode":"O433346","modelname":"Loginres"},{"modelcode":"O433349","modelname":"dmgeneralmodal"},{"modelcode":"O433352","modelname":"ErrorLog1e7e39"},{"modelcode":"O433353","modelname":"forgotpageres"},{"modelcode":"O433357","modelname":"homeres"},{"modelcode":"O433358","modelname":"Avatar"},{"modelcode":"O433364","modelname":"EmployeeProfile"},{"modelcode":"O433709","modelname":"Datafcd9a0"},{"modelcode":"O433710","modelname":"Activate"},{"modelcode":"O433712","modelname":"uisp_Up_Mbl_MobileDeviceId0b555b"},{"modelcode":"O433713","modelname":"Activationres"},{"modelcode":"O433723","modelname":"Activationresponse"},{"modelcode":"O433731","modelname":"roleres"},{"modelcode":"O433768","modelname":"geoLocation"},{"modelcode":"O433810","modelname":"types86f076"},{"modelcode":"O433811","modelname":"address_componentsf6f99c"},{"modelcode":"O433812","modelname":"location575d1b"},{"modelcode":"O433813","modelname":"northeastfce781"},{"modelcode":"O433814","modelname":"southweste8972f"},{"modelcode":"O433815","modelname":"viewportd9d0e4"},{"modelcode":"O433816","modelname":"geometry44fb65"},{"modelcode":"O433817","modelname":"plus_code5b4a1c"},{"modelcode":"O433818","modelname":"typescd5f8f"},{"modelcode":"O433819","modelname":"Locationres"},{"modelcode":"O433901","modelname":"ErrorLog7a1bee"},{"modelcode":"O433902","modelname":"locationcheck"},{"modelcode":"O433905","modelname":"GetLocationHistory"},{"modelcode":"O433914","modelname":"SavedataRes"},{"modelcode":"O433915","modelname":"attendencestatus"},{"modelcode":"O434049","modelname":"attedetails"},{"modelcode":"O434051","modelname":"ProjectCount"},{"modelcode":"O434055","modelname":"Addencevsemployee"},{"modelcode":"O434058","modelname":"ProjvsEmp"},{"modelcode":"O434061","modelname":"EmpAddence"},{"modelcode":"O434068","modelname":"Attenstatus"},{"modelcode":"O434070","modelname":"EmpAttenstaus"},{"modelcode":"O434105","modelname":"EmpAddenceclone"},{"modelcode":"O434106","modelname":"Addencevsemployeeclone"},{"modelcode":"O434107","modelname":"EmpvsProj"}],"controls":["Text_4","Text_5","Image_1","Text_6","Text_7","Text_8","Text_9","Image_2"]}
 const GlobalVariables=[]
 
module.exports = {
  PropertyJson : PropertyJson,
  Nanojson : Nanojson,
  Paramjson:Paramjson,
  Datamodel:Datamodel,
  GlobalVariables:GlobalVariables
};


